# Generated by Django 3.1.4 on 2021-01-04 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 15, 38, 53, 902853)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 15, 38, 53, 901855)),
        ),
    ]
