# Generated by Django 3.1.4 on 2021-01-04 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_auto_20210104_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FirstApp.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 15, 39, 58, 18941)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 15, 39, 58, 18941)),
        ),
    ]
