# Generated by Django 3.1.4 on 2021-01-05 07:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FirstApp', '0003_auto_20210104_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 13, 5, 25, 277762)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 13, 5, 25, 277195)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
